---
- name: Display System Bootloader Config Start
  ansible.builtin.debug:
    msg: "=== Begin System Bootloader Role Configuration ==="

# ===========================================================================
#
# ===========================================================================

- name: If Arch, Include Arch Bootloader Config
  include_tasks: arch.yaml
  when: is_arch

- name: If Debian, Include Debian Bootloader Config
  include_tasks: debian.yaml
  when: is_debian

- name: If OpenSUSE, Include OpenSUSE Bootloader Config
  include_tasks: opensuse.yaml
  when: is_opensuse

- name: If Ubuntu, Include Ubuntu Bootloader Config
  include_tasks: ubuntu.yaml
  when: is_ubuntu

  # ===========================================================================
#
# ===========================================================================

- name: Display System Bootloader Config End
  ansible.builtin.debug:
    msg: "=== End System Bootloader Role Configuration ==="
