---
# ================ Install Go ===============
- name: Install Go
  pacman:
    name:
      - go
    state: present

# ================ Install Nodejs ===========
  pacman:
    name:
      - nodejs
      - nvm
      - npm
    state: present

# ================ Install Python ===========
- name: Install Pyenv
  command: |
    curl -fsSL https://pyenv.run | bash

- name: Update .bashrc
  command: |
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
    echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
    echo 'eval "$(pyenv init - bash)"' >> ~/.bashrc

- name: Update .bash_profile
  command: |
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
    echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(pyenv init - bash)"' >> ~/.bash_profile

# ================ Install Ruby =============
- name: Install Ruby
  become: true
  pacman:
    name:
      - ruby
    state: present

# ================ Install Rust =============
- name: Install Rust
  become: true
  pacman:
    name:
      - rust
    state: present
