---
galaxy_info:
  role_name: hardware/audio
  description: Install Audio drivers and utilities (pipewire, pwvucontrol)
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - bookwork
        - bullseye
    - name: OpenSUSE
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies:
  # Requires nothing for the time being
  - role:
