galaxy_info:
  role_name: desktop/hyprland
  description: Install and configure hyprland
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - bookwork
        - bullseye
    - name: OpenSUSE
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies:
  # Requires git to be installed to clone
  # - role: system/base_packagesi
  # Requires cargo build
  - role: desktop/wayland
