---
- name: Ensure Node.js is installed (openSUSE)
  zypper:
    name: nodejs
    state: present
  become: true

- name: Ensure npm is installed (openSUSE)
  zypper:
    name: npm
    state: present
  become: true

- name: Install nvm (Node Version Manager) for openSUSE
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ ansible_facts.env.HOME }}/.nvm/nvm.sh"
  become: false
