---
galaxy_info:
  role_name: desktop_applications/steam
  description: Install Steam and configure game file storage
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - bookwork
        - bullseye
    - name: OpenSUSE
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies:
  - role: graphics/nvidia
  - role: graphics/opengl
