- name: Provision Arch Desktop
  hosts: localhost
  connection: local
  roles:
    - role: "~/OmniProvisioner/roles/arch_desktop"
      name: Arch Desktop

  vars_files:
    - ~/OmniProvisioner/roles/arch_desktop/vars/user_encr.yaml

- hosts: arch_desktop
  roles:
    - common
    - storage
    - bootloader
    - networking
    - bluetooth
    - network_storage
    - graphics
    - desktop
    - dev
    - cluster
    - ai
