-- Plugin list generator
-- Usage:
--   :lua require("geoff.plugins.list-plugins").open_buffer()   -- Open in new buffer
--   :lua require("geoff.plugins.list-plugins").save_to_file()  -- Save to current dir
--   :lua require("geoff.plugins.list-plugins").save_to_file("~/plugins.md")

local M = {}

-- Categorize plugins based on their config file names
local categories = {
	["Core & Foundation"] = { "init" },
	["UI & Appearance"] = { "alpha", "bufferline", "colorscheme", "dressing", "indent-blankline", "lualine", "nvim-tree", "transparent" },
	["Navigation & Search"] = { "telescope", "which-key", "vim-maximizer" },
	["Editing & Text Manipulation"] = { "autopairs", "comment", "surround" },
	["Git Integration"] = { "gitsigns", "lazygit" },
	["LSP & Completion"] = { "nvim-cmp", "lsp" },
	["Debugging"] = { "nvim-dap", "nvim-dap-ui", "nvim-dap-python" },
	["Diagnostics & Code Quality"] = { "trouble", "linting", "formatting" },
	["AI & Productivity"] = { "avante", "todo-comments", "auto-session" },
	["Markdown & Documentation"] = { "markdown-toc", "markview", "nvim-docs-view" },
	["Database & DevOps"] = { "dadbod", "lazydocker", "dotenv" },
	["Other"] = { "deepseek-budget" },
}

-- Friendly display names for config files
local plugin_names = {
	init = "plenary.nvim, vim-tmux-navigator",
	alpha = "alpha-nvim (startup dashboard)",
	bufferline = "bufferline.nvim (tab/buffer line)",
	colorscheme = "tokyonight (color scheme)",
	dressing = "dressing.nvim (improved UI inputs)",
	["indent-blankline"] = "indent-blankline.nvim (indentation guides)",
	lualine = "lualine.nvim (status line)",
	["nvim-tree"] = "nvim-tree.nvim (file explorer)",
	transparent = "transparent.nvim (transparent background)",
	telescope = "telescope.nvim (fuzzy finder)",
	["which-key"] = "which-key.nvim (keybinding helper)",
	["vim-maximizer"] = "vim-maximizer (window maximize)",
	autopairs = "nvim-autopairs (auto-pair brackets)",
	comment = "comment.nvim (comment toggling)",
	surround = "nvim-surround (surround text)",
	gitsigns = "gitsigns.nvim (git signs in gutter)",
	lazygit = "lazygit.nvim (LazyGit integration)",
	["nvim-cmp"] = "nvim-cmp (autocompletion)",
	lsp = "mason.nvim, nvim-lspconfig (LSP servers)",
	["nvim-dap"] = "nvim-dap (debug adapter protocol)",
	["nvim-dap-ui"] = "nvim-dap-ui (debug UI)",
	["nvim-dap-python"] = "nvim-dap-python (Python debugger)",
	trouble = "trouble.nvim (diagnostics list)",
	linting = "linting configuration",
	formatting = "formatting configuration",
	avante = "avante.nvim (AI assistant)",
	["todo-comments"] = "todo-comments.nvim (TODO highlighting)",
	["auto-session"] = "auto-session.nvim (session management)",
	["markdown-toc"] = "markdown-toc (table of contents)",
	markview = "markview.nvim (markdown preview)",
	["nvim-docs-view"] = "nvim-docs-view (documentation viewer)",
	dadbod = "dadbod.nvim (database client)",
	lazydocker = "lazydocker.nvim (Docker management)",
	dotenv = "dotenv.nvim (environment variables)",
	["deepseek-budget"] = "deepseek-budget (API budget monitor, local plugin)",
}

-- Get installed plugins from lazy.nvim
function M.get_installed_plugins()
	local ok, lazy = pcall(require, "lazy")
	if not ok then
		return nil
	end

	local plugins = lazy.plugins()
	local installed = {}
	for _, plugin in ipairs(plugins) do
		table.insert(installed, plugin.name)
	end
	return installed
end

-- Generate markdown content
function M.generate_markdown()
	local lines = {}
	table.insert(lines, "# Neovim Plugin List")
	table.insert(lines, "")
	table.insert(lines, "Generated: " .. os.date("%Y-%m-%d %H:%M:%S"))
	table.insert(lines, "")
	table.insert(lines, "> Total plugins configured: " .. #M._get_all_config_files())
	table.insert(lines, "")

	-- List by category
	for _, cat in ipairs(M._get_category_order()) do
		local configs = categories[cat]
		if configs then
			table.insert(lines, "## " .. cat)
			table.insert(lines, "")
			for _, cfg in ipairs(configs) do
				local name = plugin_names[cfg] or cfg
				table.insert(lines, "- **" .. name .. "**")
			end
			table.insert(lines, "")
		end
	end

	-- Add installed-only section if lazy.nvim is available
	local installed = M.get_installed_plugins()
	if installed then
		table.insert(lines, "## All Installed Plugins (from lazy.nvim)")
		table.insert(lines, "")
		table.insert(lines, "| # | Plugin |")
		table.insert(lines, "|---|--------|")
		for i, name in ipairs(installed) do
			table.insert(lines, "| " .. i .. " | " .. name .. " |")
		end
		table.insert(lines, "")
	end

	table.insert(lines, "---")
	table.insert(lines, "_Generated by list-plugins.lua_")

	return table.concat(lines, "\n")
end

-- Open in a new buffer
function M.open_buffer()
	local content = M.generate_markdown()
	local buf = vim.api.nvim_create_buf(false, true)
	vim.api.nvim_buf_set_lines(buf, 0, -1, false, vim.split(content, "\n"))
	vim.api.nvim_buf_set_option(buf, "filetype", "markdown")
	vim.api.nvim_buf_set_name(buf, "plugins-list.md")
	vim.api.nvim_set_current_buf(buf)
	vim.api.nvim_buf_set_option(buf, "modified", false)
	vim.notify("Plugin list generated in new buffer", vim.log.levels.INFO)
end

-- Save to file
function M.save_to_file(filepath)
	filepath = filepath or vim.fn.expand("%:p:h") .. "/plugins-list.md"
	local content = M.generate_markdown()
	local file = io.open(filepath, "w")
	if not file then
		vim.notify("Failed to open file: " .. filepath, vim.log.levels.ERROR)
		return
	end
	file:write(content)
	file:close()
	vim.notify("Plugin list saved to: " .. filepath, vim.log.levels.INFO)
end

-- Helper: get all config file keys
function M._get_all_config_files()
	local files = {}
	for _, configs in pairs(categories) do
		for _, cfg in ipairs(configs) do
			table.insert(files, cfg)
		end
	end
	return files
end

-- Helper: get category order
function M._get_category_order()
	return {
		"Core & Foundation",
		"UI & Appearance",
		"Navigation & Search",
		"Editing & Text Manipulation",
		"Git Integration",
		"LSP & Completion",
		"Debugging",
		"Diagnostics & Code Quality",
		"AI & Productivity",
		"Markdown & Documentation",
		"Database & DevOps",
		"Other",
	}
end

return M
