#preload = ~/.config/backgrounds/favbackground.jpg
# You can add more preloads for different wallpapers
# preload = ~/.config/backgrounds/another-background.jpg

# Set wallpaper for specific monitors
#wallpaper = DP-1, ~/.config/backgrounds/favbackground.jpg
#wallpaper = DP-2, ~/.config/backgrounds/favbackground.jpg

# Alternatively, you can use the same wallpaper for all monitors with:
# wallpaper = , ~/.config/backgrounds/favbackground.jpg

#wallpaper {
#    monitor = DP-1
#    path = ~/.config/backgrounds/favbackground.jpg
#    fit_mode = cover
#}

#wallpaper {
#    monitor = DP-2
#    path = ~/.config/backgrounds/favbackground.jpg
#    fit_mode = cover
#}

#ipc = on
