galaxy_info:
  role_name: desktop/widgets
  description: Install Desktop Wiget tools
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - bookwork
        - bullseye
    - name: OpenSUSE
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies:
  # Requires git to be installed to clone
  - role: common/git
  # Requires cargo build
  - role: common/rust
