---
- name: Display Desktop Applications - Inkscape Config Start
  ansible.builtin.debug:
    msg: "=== Begin Desktop Applications - Inkscape Role Configuration ==="

# ===========================================================================
#
# ===========================================================================

- name: If Arch, Include Arch Inkscape Config
  include_tasks: arch.yaml
  when: is_arch

- name: If Debian, Include Debian Inkscape Config
  include_tasks: debian.yaml
  when: is_debian

- name: If OpenSUSE, Include OpenSUSE Inkscape Config
  include_tasks: opensuse.yaml
  when: is_opensuse

- name: If Ubuntu, Include Ubuntu Inkscape Config
  include_tasks: ubuntu.yaml
  when: is_ubuntu

  # ===========================================================================
#
# ===========================================================================

- name: Display Desktop Applications - Inkscape Config End
  ansible.builtin.debug:
    msg: "=== End Desktop Applications - Inkscape Role Configuration ==="
