galaxy_info:
  role_name: common/nodejs_npm
  description: Common requirement to make sure nodejs and npm is installed
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - bookwork
        - bullseye
    - name: OpenSUSE
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies:
  # Requires git to be installed to clone
  - role:
