---
- name: Ensure gcc is installed (Ubuntu)
  apt:
    name: gcc
    state: present
    update_cache: yes
  become: true

- name: Ensure C++ compiler is installed (Debian/Ubuntu)
  apt:
    name: g++
    state: present
    update_cache: yes
  become: true
