---
- name: Display User Config Start
  ansible.builtin.debug:
    msg: "=== Begin User Role Configuration ==="

# ===========================================================================
#
# ===========================================================================

- name: OpenSuse Flag for users test
  ansible.builtin.debug:
    msg: "Configuring Users for OpenSuse ........"
  when: is_opensuse
# ===========================================================================
#
# ===========================================================================

- name: Display User Config End
  ansible.builtin.debug:
    msg: "=== End User Role Configuration ==="
