---
- name: Ensure Rust compiler is installed (Arch)
  pacman:
    name: rust
    state: present
  become: true

- name: Ensure Cargo is installed (Arch)
  pacman:
    name: cargo
    state: present
  become: true
