---
galaxy_info:
  role_name: desktop/notifications
  description: Install notifications daemon (mako)
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - bookwork
        - bullseye
    - name: OpenSUSE
      versions:
        - all
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies:
  # Requires cargo build
  #- role: common/rust
  # Requires wayand-protocol and wayland-client and cargo
  - role: desktop/wayland
