- name: Install Neovim
  become: true
  pacman:
    name:
      - neovim
    state: present

- name: Install requirements for telescope.nvim (ripgrep, fd, fzf, devicons)
  become: true
  pacman:
    name:
      - ripgrep

- name: Install Lazygit
  become: true
  pacman:
    name:
      - lazygit
    state: present
