---
- name: Validate and restart SSH
  become: true
  block:
    - name: Validate sshd_config syntax before restart
      ansible.builtin.command: sshd -t
      changed_when: false

    - name: Restart SSH service
      ansible.builtin.systemd:
        name: sshd
        state: restarted

- name: Restart fail2ban
  become: true
  systemd:
    name: fail2ban
    state: restarted
